server.servlet.context-path=/api-server
server.port=3012
domain=https://datareadings.nextwavemonitoring.com

#datalogger.cronjob.active=false
#alert.nocomm.cronjob.active=false
#alert.noproduction.cronjob.active=false
#alert.field.cronjob.active=false
#solaredge.cronjob.auto_backfill=false
