package com.nwm.api.entities;

public class ModelInaccessPPCV1Entity extends ModelBaseEntity {
	private double ANALOG_INPUT_ACTIVE_POWER_FEEDBACK;
	private double ANALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK;
	private double ANALOG_INPUT_POWER_FACTOR_FEEDBACK;
	private double ANALOG_INPUT_REACTIVE_POWER_FEEDBACK;
	private double ANALOG_OUTPUT_ACTIVE_POWER_SETPOINT;
	private double ANALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT;
	private double ANALOG_OUTPUT_POWER_FACTOR_SETPOINT;
	private double ANALOG_OUTPUT_REACTIVE_POWER_SETPOINT;
	private double DIGITAL_INPUT_AUTO_VOLT_REG_STAT;
	private double DIGITAL_INPUT_FREQ_CTRL_EVENT_STAT;
	private double DIGITAL_INPUT_FREQ_CTRL_STAT;
	private double DIGITAL_INPUT_LOCAL_REMOTE_STAT;
	private double DIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT;
	private double DIGITAL_INPUT_P_CTRL_STAT;
	private double DIGITAL_INPUT_PF_CTRL_STAT;
	private double DIGITAL_INPUT_Q_CTRL_STAT;
	private double DIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF;
	private double DIGITAL_OUTPUT_AUTO_VOLT_REG_SET;
	private double DIGITAL_OUTPUT_FREQ_CTRL_SET;
	private double DIGITAL_OUTPUT_LOCAL_REMOTE_SET;
	private double DIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET;
	private double DIGITAL_OUTPUT_P_CTRL_SET;
	private double DIGITAL_OUTPUT_P_CTRL_SET_RELEASE;
	private double DIGITAL_OUTPUT_PF_CTRL_SET;
	private double DIGITAL_OUTPUT_Q_CTRL_SET;
	private double DIGITAL_OUTPUT_Q_CTRL_SET_RELEASE;
	public double getANALOG_INPUT_ACTIVE_POWER_FEEDBACK() {
		return ANALOG_INPUT_ACTIVE_POWER_FEEDBACK;
	}
	public void setANALOG_INPUT_ACTIVE_POWER_FEEDBACK(double aNALOG_INPUT_ACTIVE_POWER_FEEDBACK) {
		ANALOG_INPUT_ACTIVE_POWER_FEEDBACK = aNALOG_INPUT_ACTIVE_POWER_FEEDBACK;
	}
	public double getANALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK() {
		return ANALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK;
	}
	public void setANALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK(double aNALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK) {
		ANALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK = aNALOG_INPUT_AUTO_VOLT_CTRL_FEEDBACK;
	}
	public double getANALOG_INPUT_POWER_FACTOR_FEEDBACK() {
		return ANALOG_INPUT_POWER_FACTOR_FEEDBACK;
	}
	public void setANALOG_INPUT_POWER_FACTOR_FEEDBACK(double aNALOG_INPUT_POWER_FACTOR_FEEDBACK) {
		ANALOG_INPUT_POWER_FACTOR_FEEDBACK = aNALOG_INPUT_POWER_FACTOR_FEEDBACK;
	}
	public double getANALOG_INPUT_REACTIVE_POWER_FEEDBACK() {
		return ANALOG_INPUT_REACTIVE_POWER_FEEDBACK;
	}
	public void setANALOG_INPUT_REACTIVE_POWER_FEEDBACK(double aNALOG_INPUT_REACTIVE_POWER_FEEDBACK) {
		ANALOG_INPUT_REACTIVE_POWER_FEEDBACK = aNALOG_INPUT_REACTIVE_POWER_FEEDBACK;
	}
	public double getANALOG_OUTPUT_ACTIVE_POWER_SETPOINT() {
		return ANALOG_OUTPUT_ACTIVE_POWER_SETPOINT;
	}
	public void setANALOG_OUTPUT_ACTIVE_POWER_SETPOINT(double aNALOG_OUTPUT_ACTIVE_POWER_SETPOINT) {
		ANALOG_OUTPUT_ACTIVE_POWER_SETPOINT = aNALOG_OUTPUT_ACTIVE_POWER_SETPOINT;
	}
	public double getANALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT() {
		return ANALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT;
	}
	public void setANALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT(double aNALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT) {
		ANALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT = aNALOG_OUTPUT_AUTO_VOLT_CTRL_SETPOINT;
	}
	public double getANALOG_OUTPUT_POWER_FACTOR_SETPOINT() {
		return ANALOG_OUTPUT_POWER_FACTOR_SETPOINT;
	}
	public void setANALOG_OUTPUT_POWER_FACTOR_SETPOINT(double aNALOG_OUTPUT_POWER_FACTOR_SETPOINT) {
		ANALOG_OUTPUT_POWER_FACTOR_SETPOINT = aNALOG_OUTPUT_POWER_FACTOR_SETPOINT;
	}
	public double getANALOG_OUTPUT_REACTIVE_POWER_SETPOINT() {
		return ANALOG_OUTPUT_REACTIVE_POWER_SETPOINT;
	}
	public void setANALOG_OUTPUT_REACTIVE_POWER_SETPOINT(double aNALOG_OUTPUT_REACTIVE_POWER_SETPOINT) {
		ANALOG_OUTPUT_REACTIVE_POWER_SETPOINT = aNALOG_OUTPUT_REACTIVE_POWER_SETPOINT;
	}
	public double getDIGITAL_INPUT_AUTO_VOLT_REG_STAT() {
		return DIGITAL_INPUT_AUTO_VOLT_REG_STAT;
	}
	public void setDIGITAL_INPUT_AUTO_VOLT_REG_STAT(double dIGITAL_INPUT_AUTO_VOLT_REG_STAT) {
		DIGITAL_INPUT_AUTO_VOLT_REG_STAT = dIGITAL_INPUT_AUTO_VOLT_REG_STAT;
	}
	public double getDIGITAL_INPUT_FREQ_CTRL_EVENT_STAT() {
		return DIGITAL_INPUT_FREQ_CTRL_EVENT_STAT;
	}
	public void setDIGITAL_INPUT_FREQ_CTRL_EVENT_STAT(double dIGITAL_INPUT_FREQ_CTRL_EVENT_STAT) {
		DIGITAL_INPUT_FREQ_CTRL_EVENT_STAT = dIGITAL_INPUT_FREQ_CTRL_EVENT_STAT;
	}
	public double getDIGITAL_INPUT_FREQ_CTRL_STAT() {
		return DIGITAL_INPUT_FREQ_CTRL_STAT;
	}
	public void setDIGITAL_INPUT_FREQ_CTRL_STAT(double dIGITAL_INPUT_FREQ_CTRL_STAT) {
		DIGITAL_INPUT_FREQ_CTRL_STAT = dIGITAL_INPUT_FREQ_CTRL_STAT;
	}
	public double getDIGITAL_INPUT_LOCAL_REMOTE_STAT() {
		return DIGITAL_INPUT_LOCAL_REMOTE_STAT;
	}
	public void setDIGITAL_INPUT_LOCAL_REMOTE_STAT(double dIGITAL_INPUT_LOCAL_REMOTE_STAT) {
		DIGITAL_INPUT_LOCAL_REMOTE_STAT = dIGITAL_INPUT_LOCAL_REMOTE_STAT;
	}
	public double getDIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT() {
		return DIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT;
	}
	public void setDIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT(double dIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT) {
		DIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT = dIGITAL_INPUT_P_CTRL_RAMP_RATE_STAT;
	}
	public double getDIGITAL_INPUT_P_CTRL_STAT() {
		return DIGITAL_INPUT_P_CTRL_STAT;
	}
	public void setDIGITAL_INPUT_P_CTRL_STAT(double dIGITAL_INPUT_P_CTRL_STAT) {
		DIGITAL_INPUT_P_CTRL_STAT = dIGITAL_INPUT_P_CTRL_STAT;
	}
	public double getDIGITAL_INPUT_PF_CTRL_STAT() {
		return DIGITAL_INPUT_PF_CTRL_STAT;
	}
	public void setDIGITAL_INPUT_PF_CTRL_STAT(double dIGITAL_INPUT_PF_CTRL_STAT) {
		DIGITAL_INPUT_PF_CTRL_STAT = dIGITAL_INPUT_PF_CTRL_STAT;
	}
	public double getDIGITAL_INPUT_Q_CTRL_STAT() {
		return DIGITAL_INPUT_Q_CTRL_STAT;
	}
	public void setDIGITAL_INPUT_Q_CTRL_STAT(double dIGITAL_INPUT_Q_CTRL_STAT) {
		DIGITAL_INPUT_Q_CTRL_STAT = dIGITAL_INPUT_Q_CTRL_STAT;
	}
	public double getDIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF() {
		return DIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF;
	}
	public void setDIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF(double dIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF) {
		DIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF = dIGITAL_OUTPUT_ALL_INVERTERS_ON_OFF;
	}
	public double getDIGITAL_OUTPUT_AUTO_VOLT_REG_SET() {
		return DIGITAL_OUTPUT_AUTO_VOLT_REG_SET;
	}
	public void setDIGITAL_OUTPUT_AUTO_VOLT_REG_SET(double dIGITAL_OUTPUT_AUTO_VOLT_REG_SET) {
		DIGITAL_OUTPUT_AUTO_VOLT_REG_SET = dIGITAL_OUTPUT_AUTO_VOLT_REG_SET;
	}
	public double getDIGITAL_OUTPUT_FREQ_CTRL_SET() {
		return DIGITAL_OUTPUT_FREQ_CTRL_SET;
	}
	public void setDIGITAL_OUTPUT_FREQ_CTRL_SET(double dIGITAL_OUTPUT_FREQ_CTRL_SET) {
		DIGITAL_OUTPUT_FREQ_CTRL_SET = dIGITAL_OUTPUT_FREQ_CTRL_SET;
	}
	public double getDIGITAL_OUTPUT_LOCAL_REMOTE_SET() {
		return DIGITAL_OUTPUT_LOCAL_REMOTE_SET;
	}
	public void setDIGITAL_OUTPUT_LOCAL_REMOTE_SET(double dIGITAL_OUTPUT_LOCAL_REMOTE_SET) {
		DIGITAL_OUTPUT_LOCAL_REMOTE_SET = dIGITAL_OUTPUT_LOCAL_REMOTE_SET;
	}
	public double getDIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET() {
		return DIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET;
	}
	public void setDIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET(double dIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET) {
		DIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET = dIGITAL_OUTPUT_P_CTRL_RAMP_RATE_SET;
	}
	public double getDIGITAL_OUTPUT_P_CTRL_SET() {
		return DIGITAL_OUTPUT_P_CTRL_SET;
	}
	public void setDIGITAL_OUTPUT_P_CTRL_SET(double dIGITAL_OUTPUT_P_CTRL_SET) {
		DIGITAL_OUTPUT_P_CTRL_SET = dIGITAL_OUTPUT_P_CTRL_SET;
	}
	public double getDIGITAL_OUTPUT_P_CTRL_SET_RELEASE() {
		return DIGITAL_OUTPUT_P_CTRL_SET_RELEASE;
	}
	public void setDIGITAL_OUTPUT_P_CTRL_SET_RELEASE(double dIGITAL_OUTPUT_P_CTRL_SET_RELEASE) {
		DIGITAL_OUTPUT_P_CTRL_SET_RELEASE = dIGITAL_OUTPUT_P_CTRL_SET_RELEASE;
	}
	public double getDIGITAL_OUTPUT_PF_CTRL_SET() {
		return DIGITAL_OUTPUT_PF_CTRL_SET;
	}
	public void setDIGITAL_OUTPUT_PF_CTRL_SET(double dIGITAL_OUTPUT_PF_CTRL_SET) {
		DIGITAL_OUTPUT_PF_CTRL_SET = dIGITAL_OUTPUT_PF_CTRL_SET;
	}
	public double getDIGITAL_OUTPUT_Q_CTRL_SET() {
		return DIGITAL_OUTPUT_Q_CTRL_SET;
	}
	public void setDIGITAL_OUTPUT_Q_CTRL_SET(double dIGITAL_OUTPUT_Q_CTRL_SET) {
		DIGITAL_OUTPUT_Q_CTRL_SET = dIGITAL_OUTPUT_Q_CTRL_SET;
	}
	public double getDIGITAL_OUTPUT_Q_CTRL_SET_RELEASE() {
		return DIGITAL_OUTPUT_Q_CTRL_SET_RELEASE;
	}
	public void setDIGITAL_OUTPUT_Q_CTRL_SET_RELEASE(double dIGITAL_OUTPUT_Q_CTRL_SET_RELEASE) {
		DIGITAL_OUTPUT_Q_CTRL_SET_RELEASE = dIGITAL_OUTPUT_Q_CTRL_SET_RELEASE;
	}
	
	
	
	
}
