package com.nwm.api.entities;

public class ModelIDECPLCEntity extends ModelBaseEntity {
	private double ACTIVE_POWER_W_REF_TO_FREQ_TOGGLE;
	private double DUMMY_FREQUENCY;
	private double FEEDBACK_VRE_P_CTRL_TOGGLE;
	private double GRADIENT_CONSTRAINT_ACTIVE;
	private double REMOTE_LOCAL;
	private double COMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET;
	private double COMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET;
	private double COMPUTED_INVERTERS_QTY;
	private double COMPUTED_MAX_COMPUTED_MVAR;
	private double COMPUTED_MIN_COMPUTED_MVAR;
	private double COMPUTED_POA_IRRADIANCE;
	private double COMPUTED_PV_MOD_TEMP_AVE;
	private double LOCAL_AI_ACTIVE_POWER_FEEDBACK;
	private double LOCAL_AI_POWER_FACTOR_FEEDBACK;
	private double LOCAL_AI_REACTIVE_POWER_FEEDBACK;
	private double LOCAL_AI_VOLTAGE_FEEDBACK;
	private double LOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT;
	private double LOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	private double LOCAL_DO_LOC_ACTIVE_POWER_START_STOP;
	private double LOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD;
	private double LOCAL_DO_LOC_PF_CTRL_MODE;
	private double LOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE;
	private double LOCAL_DO_LOC_VOLTAGE_CTRL_MODE;
	private double LOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL;
	private double LOCAL_DO_LOC_VRE_VOLT_CTRL;
	private double NGCP_AI_ACTIVE_POWER_FEEDBACK;
	private double NGCP_AI_POWER_FACTOR_FEEDBACK;
	private double NGCP_AI_REACTIVE_POWER_FEEDBACK;
	private double NGCP_AI_VOLTAGE_FEEDBACK;
	private double NGCP_AO_ACTIVE_POWER_SETPOINT;
	private double NGCP_AO_POWER_FACTOR_SETPOINT;
	private double NGCP_AO_REACTIVE_POWER_SETPOINT;
	private double NGCP_AO_VOLTAGE_SETPOINT;
	private double NGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT;
	private double NGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	private double NGCP_DI_STAT_ACTIVE_POWER_START_STOP;
	private double NGCP_DI_STAT_FREE_ACTIVE_POWER_PROD;
	private double NGCP_DI_STAT_PF_CTRL_MODE;
	private double NGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE;
	private double NGCP_DI_STAT_VOLTAGE_CTRL_MODE;
	private double NGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL;
	private double NGCP_DI_STAT_VRE_VOLT_CTRL;
	private double NGCP_DO_SET_ACTIVE_POWER_CONSTRAINT;
	private double NGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	private double NGCP_DO_SET_ACTIVE_POWER_START_STOP;
	private double NGCP_DO_SET_FREE_ACTIVE_POWER_PROD;
	private double NGCP_DO_SET_PF_CTRL_MODE;
	private double NGCP_DO_SET_REACTIVE_POWER_CTRL_MODE;
	private double NGCP_DO_SET_VOLTAGE_CTRL_MODE;
	private double NGCP_DO_SET_VRE_ACTIVE_POWER_CTRL;
	private double NGCP_DO_SET_VRE_VOLT_CTRL;
	public double getACTIVE_POWER_W_REF_TO_FREQ_TOGGLE() {
		return ACTIVE_POWER_W_REF_TO_FREQ_TOGGLE;
	}
	public void setACTIVE_POWER_W_REF_TO_FREQ_TOGGLE(double aCTIVE_POWER_W_REF_TO_FREQ_TOGGLE) {
		ACTIVE_POWER_W_REF_TO_FREQ_TOGGLE = aCTIVE_POWER_W_REF_TO_FREQ_TOGGLE;
	}
	public double getDUMMY_FREQUENCY() {
		return DUMMY_FREQUENCY;
	}
	public void setDUMMY_FREQUENCY(double dUMMY_FREQUENCY) {
		DUMMY_FREQUENCY = dUMMY_FREQUENCY;
	}
	public double getFEEDBACK_VRE_P_CTRL_TOGGLE() {
		return FEEDBACK_VRE_P_CTRL_TOGGLE;
	}
	public void setFEEDBACK_VRE_P_CTRL_TOGGLE(double fEEDBACK_VRE_P_CTRL_TOGGLE) {
		FEEDBACK_VRE_P_CTRL_TOGGLE = fEEDBACK_VRE_P_CTRL_TOGGLE;
	}
	public double getGRADIENT_CONSTRAINT_ACTIVE() {
		return GRADIENT_CONSTRAINT_ACTIVE;
	}
	public void setGRADIENT_CONSTRAINT_ACTIVE(double gRADIENT_CONSTRAINT_ACTIVE) {
		GRADIENT_CONSTRAINT_ACTIVE = gRADIENT_CONSTRAINT_ACTIVE;
	}
	public double getREMOTE_LOCAL() {
		return REMOTE_LOCAL;
	}
	public void setREMOTE_LOCAL(double rEMOTE_LOCAL) {
		REMOTE_LOCAL = rEMOTE_LOCAL;
	}
	public double getCOMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET() {
		return COMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET;
	}
	public void setCOMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET(double cOMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET) {
		COMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET = cOMPUTED_FREQ_REGULATED_ACTIVE_POWER_SET;
	}
	public double getCOMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET() {
		return COMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET;
	}
	public void setCOMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET(double cOMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET) {
		COMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET = cOMPUTED_GRADIENT_CONS_ACTIVE_POWER_SET;
	}
	public double getCOMPUTED_INVERTERS_QTY() {
		return COMPUTED_INVERTERS_QTY;
	}
	public void setCOMPUTED_INVERTERS_QTY(double cOMPUTED_INVERTERS_QTY) {
		COMPUTED_INVERTERS_QTY = cOMPUTED_INVERTERS_QTY;
	}
	public double getCOMPUTED_MAX_COMPUTED_MVAR() {
		return COMPUTED_MAX_COMPUTED_MVAR;
	}
	public void setCOMPUTED_MAX_COMPUTED_MVAR(double cOMPUTED_MAX_COMPUTED_MVAR) {
		COMPUTED_MAX_COMPUTED_MVAR = cOMPUTED_MAX_COMPUTED_MVAR;
	}
	public double getCOMPUTED_MIN_COMPUTED_MVAR() {
		return COMPUTED_MIN_COMPUTED_MVAR;
	}
	public void setCOMPUTED_MIN_COMPUTED_MVAR(double cOMPUTED_MIN_COMPUTED_MVAR) {
		COMPUTED_MIN_COMPUTED_MVAR = cOMPUTED_MIN_COMPUTED_MVAR;
	}
	public double getCOMPUTED_POA_IRRADIANCE() {
		return COMPUTED_POA_IRRADIANCE;
	}
	public void setCOMPUTED_POA_IRRADIANCE(double cOMPUTED_POA_IRRADIANCE) {
		COMPUTED_POA_IRRADIANCE = cOMPUTED_POA_IRRADIANCE;
	}
	public double getCOMPUTED_PV_MOD_TEMP_AVE() {
		return COMPUTED_PV_MOD_TEMP_AVE;
	}
	public void setCOMPUTED_PV_MOD_TEMP_AVE(double cOMPUTED_PV_MOD_TEMP_AVE) {
		COMPUTED_PV_MOD_TEMP_AVE = cOMPUTED_PV_MOD_TEMP_AVE;
	}
	public double getLOCAL_AI_ACTIVE_POWER_FEEDBACK() {
		return LOCAL_AI_ACTIVE_POWER_FEEDBACK;
	}
	public void setLOCAL_AI_ACTIVE_POWER_FEEDBACK(double lOCAL_AI_ACTIVE_POWER_FEEDBACK) {
		LOCAL_AI_ACTIVE_POWER_FEEDBACK = lOCAL_AI_ACTIVE_POWER_FEEDBACK;
	}
	public double getLOCAL_AI_POWER_FACTOR_FEEDBACK() {
		return LOCAL_AI_POWER_FACTOR_FEEDBACK;
	}
	public void setLOCAL_AI_POWER_FACTOR_FEEDBACK(double lOCAL_AI_POWER_FACTOR_FEEDBACK) {
		LOCAL_AI_POWER_FACTOR_FEEDBACK = lOCAL_AI_POWER_FACTOR_FEEDBACK;
	}
	public double getLOCAL_AI_REACTIVE_POWER_FEEDBACK() {
		return LOCAL_AI_REACTIVE_POWER_FEEDBACK;
	}
	public void setLOCAL_AI_REACTIVE_POWER_FEEDBACK(double lOCAL_AI_REACTIVE_POWER_FEEDBACK) {
		LOCAL_AI_REACTIVE_POWER_FEEDBACK = lOCAL_AI_REACTIVE_POWER_FEEDBACK;
	}
	public double getLOCAL_AI_VOLTAGE_FEEDBACK() {
		return LOCAL_AI_VOLTAGE_FEEDBACK;
	}
	public void setLOCAL_AI_VOLTAGE_FEEDBACK(double lOCAL_AI_VOLTAGE_FEEDBACK) {
		LOCAL_AI_VOLTAGE_FEEDBACK = lOCAL_AI_VOLTAGE_FEEDBACK;
	}
	public double getLOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT() {
		return LOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT;
	}
	public void setLOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT(double lOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT) {
		LOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT = lOCAL_DO_LOC_ACTIVE_POWER_CONSTRAINT;
	}
	public double getLOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT() {
		return LOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public void setLOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT(double lOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT) {
		LOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT = lOCAL_DO_LOC_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public double getLOCAL_DO_LOC_ACTIVE_POWER_START_STOP() {
		return LOCAL_DO_LOC_ACTIVE_POWER_START_STOP;
	}
	public void setLOCAL_DO_LOC_ACTIVE_POWER_START_STOP(double lOCAL_DO_LOC_ACTIVE_POWER_START_STOP) {
		LOCAL_DO_LOC_ACTIVE_POWER_START_STOP = lOCAL_DO_LOC_ACTIVE_POWER_START_STOP;
	}
	public double getLOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD() {
		return LOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD;
	}
	public void setLOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD(double lOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD) {
		LOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD = lOCAL_DO_LOC_FREE_ACTIVE_POWER_PROD;
	}
	public double getLOCAL_DO_LOC_PF_CTRL_MODE() {
		return LOCAL_DO_LOC_PF_CTRL_MODE;
	}
	public void setLOCAL_DO_LOC_PF_CTRL_MODE(double lOCAL_DO_LOC_PF_CTRL_MODE) {
		LOCAL_DO_LOC_PF_CTRL_MODE = lOCAL_DO_LOC_PF_CTRL_MODE;
	}
	public double getLOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE() {
		return LOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE;
	}
	public void setLOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE(double lOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE) {
		LOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE = lOCAL_DO_LOC_REACTIVE_POWER_CTRL_MODE;
	}
	public double getLOCAL_DO_LOC_VOLTAGE_CTRL_MODE() {
		return LOCAL_DO_LOC_VOLTAGE_CTRL_MODE;
	}
	public void setLOCAL_DO_LOC_VOLTAGE_CTRL_MODE(double lOCAL_DO_LOC_VOLTAGE_CTRL_MODE) {
		LOCAL_DO_LOC_VOLTAGE_CTRL_MODE = lOCAL_DO_LOC_VOLTAGE_CTRL_MODE;
	}
	public double getLOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL() {
		return LOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL;
	}
	public void setLOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL(double lOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL) {
		LOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL = lOCAL_DO_LOC_VRE_ACTIVE_POWER_CTRL;
	}
	public double getLOCAL_DO_LOC_VRE_VOLT_CTRL() {
		return LOCAL_DO_LOC_VRE_VOLT_CTRL;
	}
	public void setLOCAL_DO_LOC_VRE_VOLT_CTRL(double lOCAL_DO_LOC_VRE_VOLT_CTRL) {
		LOCAL_DO_LOC_VRE_VOLT_CTRL = lOCAL_DO_LOC_VRE_VOLT_CTRL;
	}
	public double getNGCP_AI_ACTIVE_POWER_FEEDBACK() {
		return NGCP_AI_ACTIVE_POWER_FEEDBACK;
	}
	public void setNGCP_AI_ACTIVE_POWER_FEEDBACK(double nGCP_AI_ACTIVE_POWER_FEEDBACK) {
		NGCP_AI_ACTIVE_POWER_FEEDBACK = nGCP_AI_ACTIVE_POWER_FEEDBACK;
	}
	public double getNGCP_AI_POWER_FACTOR_FEEDBACK() {
		return NGCP_AI_POWER_FACTOR_FEEDBACK;
	}
	public void setNGCP_AI_POWER_FACTOR_FEEDBACK(double nGCP_AI_POWER_FACTOR_FEEDBACK) {
		NGCP_AI_POWER_FACTOR_FEEDBACK = nGCP_AI_POWER_FACTOR_FEEDBACK;
	}
	public double getNGCP_AI_REACTIVE_POWER_FEEDBACK() {
		return NGCP_AI_REACTIVE_POWER_FEEDBACK;
	}
	public void setNGCP_AI_REACTIVE_POWER_FEEDBACK(double nGCP_AI_REACTIVE_POWER_FEEDBACK) {
		NGCP_AI_REACTIVE_POWER_FEEDBACK = nGCP_AI_REACTIVE_POWER_FEEDBACK;
	}
	public double getNGCP_AI_VOLTAGE_FEEDBACK() {
		return NGCP_AI_VOLTAGE_FEEDBACK;
	}
	public void setNGCP_AI_VOLTAGE_FEEDBACK(double nGCP_AI_VOLTAGE_FEEDBACK) {
		NGCP_AI_VOLTAGE_FEEDBACK = nGCP_AI_VOLTAGE_FEEDBACK;
	}
	public double getNGCP_AO_ACTIVE_POWER_SETPOINT() {
		return NGCP_AO_ACTIVE_POWER_SETPOINT;
	}
	public void setNGCP_AO_ACTIVE_POWER_SETPOINT(double nGCP_AO_ACTIVE_POWER_SETPOINT) {
		NGCP_AO_ACTIVE_POWER_SETPOINT = nGCP_AO_ACTIVE_POWER_SETPOINT;
	}
	public double getNGCP_AO_POWER_FACTOR_SETPOINT() {
		return NGCP_AO_POWER_FACTOR_SETPOINT;
	}
	public void setNGCP_AO_POWER_FACTOR_SETPOINT(double nGCP_AO_POWER_FACTOR_SETPOINT) {
		NGCP_AO_POWER_FACTOR_SETPOINT = nGCP_AO_POWER_FACTOR_SETPOINT;
	}
	public double getNGCP_AO_REACTIVE_POWER_SETPOINT() {
		return NGCP_AO_REACTIVE_POWER_SETPOINT;
	}
	public void setNGCP_AO_REACTIVE_POWER_SETPOINT(double nGCP_AO_REACTIVE_POWER_SETPOINT) {
		NGCP_AO_REACTIVE_POWER_SETPOINT = nGCP_AO_REACTIVE_POWER_SETPOINT;
	}
	public double getNGCP_AO_VOLTAGE_SETPOINT() {
		return NGCP_AO_VOLTAGE_SETPOINT;
	}
	public void setNGCP_AO_VOLTAGE_SETPOINT(double nGCP_AO_VOLTAGE_SETPOINT) {
		NGCP_AO_VOLTAGE_SETPOINT = nGCP_AO_VOLTAGE_SETPOINT;
	}
	public double getNGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT() {
		return NGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT;
	}
	public void setNGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT(double nGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT) {
		NGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT = nGCP_DI_STAT_ACTIVE_POWER_CONSTRAINT;
	}
	public double getNGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT() {
		return NGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public void setNGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT(double nGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT) {
		NGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT = nGCP_DI_STAT_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public double getNGCP_DI_STAT_ACTIVE_POWER_START_STOP() {
		return NGCP_DI_STAT_ACTIVE_POWER_START_STOP;
	}
	public void setNGCP_DI_STAT_ACTIVE_POWER_START_STOP(double nGCP_DI_STAT_ACTIVE_POWER_START_STOP) {
		NGCP_DI_STAT_ACTIVE_POWER_START_STOP = nGCP_DI_STAT_ACTIVE_POWER_START_STOP;
	}
	public double getNGCP_DI_STAT_FREE_ACTIVE_POWER_PROD() {
		return NGCP_DI_STAT_FREE_ACTIVE_POWER_PROD;
	}
	public void setNGCP_DI_STAT_FREE_ACTIVE_POWER_PROD(double nGCP_DI_STAT_FREE_ACTIVE_POWER_PROD) {
		NGCP_DI_STAT_FREE_ACTIVE_POWER_PROD = nGCP_DI_STAT_FREE_ACTIVE_POWER_PROD;
	}
	public double getNGCP_DI_STAT_PF_CTRL_MODE() {
		return NGCP_DI_STAT_PF_CTRL_MODE;
	}
	public void setNGCP_DI_STAT_PF_CTRL_MODE(double nGCP_DI_STAT_PF_CTRL_MODE) {
		NGCP_DI_STAT_PF_CTRL_MODE = nGCP_DI_STAT_PF_CTRL_MODE;
	}
	public double getNGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE() {
		return NGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE;
	}
	public void setNGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE(double nGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE) {
		NGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE = nGCP_DI_STAT_REACTIVE_POWER_CTRL_MODE;
	}
	public double getNGCP_DI_STAT_VOLTAGE_CTRL_MODE() {
		return NGCP_DI_STAT_VOLTAGE_CTRL_MODE;
	}
	public void setNGCP_DI_STAT_VOLTAGE_CTRL_MODE(double nGCP_DI_STAT_VOLTAGE_CTRL_MODE) {
		NGCP_DI_STAT_VOLTAGE_CTRL_MODE = nGCP_DI_STAT_VOLTAGE_CTRL_MODE;
	}
	public double getNGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL() {
		return NGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL;
	}
	public void setNGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL(double nGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL) {
		NGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL = nGCP_DI_STAT_VRE_ACTIVE_POWER_CTRL;
	}
	public double getNGCP_DI_STAT_VRE_VOLT_CTRL() {
		return NGCP_DI_STAT_VRE_VOLT_CTRL;
	}
	public void setNGCP_DI_STAT_VRE_VOLT_CTRL(double nGCP_DI_STAT_VRE_VOLT_CTRL) {
		NGCP_DI_STAT_VRE_VOLT_CTRL = nGCP_DI_STAT_VRE_VOLT_CTRL;
	}
	public double getNGCP_DO_SET_ACTIVE_POWER_CONSTRAINT() {
		return NGCP_DO_SET_ACTIVE_POWER_CONSTRAINT;
	}
	public void setNGCP_DO_SET_ACTIVE_POWER_CONSTRAINT(double nGCP_DO_SET_ACTIVE_POWER_CONSTRAINT) {
		NGCP_DO_SET_ACTIVE_POWER_CONSTRAINT = nGCP_DO_SET_ACTIVE_POWER_CONSTRAINT;
	}
	public double getNGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT() {
		return NGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public void setNGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT(double nGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT) {
		NGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT = nGCP_DO_SET_ACTIVE_POWER_GRADIENT_CONSTRAINT;
	}
	public double getNGCP_DO_SET_ACTIVE_POWER_START_STOP() {
		return NGCP_DO_SET_ACTIVE_POWER_START_STOP;
	}
	public void setNGCP_DO_SET_ACTIVE_POWER_START_STOP(double nGCP_DO_SET_ACTIVE_POWER_START_STOP) {
		NGCP_DO_SET_ACTIVE_POWER_START_STOP = nGCP_DO_SET_ACTIVE_POWER_START_STOP;
	}
	public double getNGCP_DO_SET_FREE_ACTIVE_POWER_PROD() {
		return NGCP_DO_SET_FREE_ACTIVE_POWER_PROD;
	}
	public void setNGCP_DO_SET_FREE_ACTIVE_POWER_PROD(double nGCP_DO_SET_FREE_ACTIVE_POWER_PROD) {
		NGCP_DO_SET_FREE_ACTIVE_POWER_PROD = nGCP_DO_SET_FREE_ACTIVE_POWER_PROD;
	}
	public double getNGCP_DO_SET_PF_CTRL_MODE() {
		return NGCP_DO_SET_PF_CTRL_MODE;
	}
	public void setNGCP_DO_SET_PF_CTRL_MODE(double nGCP_DO_SET_PF_CTRL_MODE) {
		NGCP_DO_SET_PF_CTRL_MODE = nGCP_DO_SET_PF_CTRL_MODE;
	}
	public double getNGCP_DO_SET_REACTIVE_POWER_CTRL_MODE() {
		return NGCP_DO_SET_REACTIVE_POWER_CTRL_MODE;
	}
	public void setNGCP_DO_SET_REACTIVE_POWER_CTRL_MODE(double nGCP_DO_SET_REACTIVE_POWER_CTRL_MODE) {
		NGCP_DO_SET_REACTIVE_POWER_CTRL_MODE = nGCP_DO_SET_REACTIVE_POWER_CTRL_MODE;
	}
	public double getNGCP_DO_SET_VOLTAGE_CTRL_MODE() {
		return NGCP_DO_SET_VOLTAGE_CTRL_MODE;
	}
	public void setNGCP_DO_SET_VOLTAGE_CTRL_MODE(double nGCP_DO_SET_VOLTAGE_CTRL_MODE) {
		NGCP_DO_SET_VOLTAGE_CTRL_MODE = nGCP_DO_SET_VOLTAGE_CTRL_MODE;
	}
	public double getNGCP_DO_SET_VRE_ACTIVE_POWER_CTRL() {
		return NGCP_DO_SET_VRE_ACTIVE_POWER_CTRL;
	}
	public void setNGCP_DO_SET_VRE_ACTIVE_POWER_CTRL(double nGCP_DO_SET_VRE_ACTIVE_POWER_CTRL) {
		NGCP_DO_SET_VRE_ACTIVE_POWER_CTRL = nGCP_DO_SET_VRE_ACTIVE_POWER_CTRL;
	}
	public double getNGCP_DO_SET_VRE_VOLT_CTRL() {
		return NGCP_DO_SET_VRE_VOLT_CTRL;
	}
	public void setNGCP_DO_SET_VRE_VOLT_CTRL(double nGCP_DO_SET_VRE_VOLT_CTRL) {
		NGCP_DO_SET_VRE_VOLT_CTRL = nGCP_DO_SET_VRE_VOLT_CTRL;
	}
	
	
}
